spring.application.name=Gateway

server.port=9000
#El apigateway es un componente en la arquitectura de de Microservicios que actua como un punto de entrada unico
#Sirve para gestionar todas las solicitudes de microservicios, su funcion es intermediar, enrutar y gestionar
#habilitar como un cliente de eureka
spring.cloud.service-registry.auto-registration.enable=true

#configuracion de losrsvicios que va a registrar y gestionar
#Cliente
spring.cloud.gateway.server.webmvc.routes[0].id=Cliente
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8010
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/Clientes/**

#Departamento
spring.cloud.gateway.server.webmvc.routes[1].id=Departamento
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8013
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/Departamento/**

#Empleado
spring.cloud.gateway.server.webmvc.routes[2].id=Empleado
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8012
spring.cloud.gateway.server.webmvc.routes[2].predicates=Path=/Empleados/**

#Producto
spring.cloud.gateway.server.webmvc.routes[3].id=Producto
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8011
spring.cloud.gateway.server.webmvc.routes[3].predicates=Path=/Productos/**

#Tienda
spring.cloud.gateway.server.webmvc.routes[4].id=Tienda
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8015
spring.cloud.gateway.server.webmvc.routes[4].predicates=Path=/T/**