SELECT * FROM mascota;
DROP TABLE TAREA;
CREATE TABLE DUENO (
    ID_DUENO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    TELEFONO NVARCHAR2(20)
);

CREATE TABLE MASCOTA (
    ID_MASCOTA NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    ESPECIE NVARCHAR2(50),
    EDAD NUMBER(3),
    DUENO_ID NUMBER,
    CONSTRAINT FK_MASCOTA_DUENO FOREIGN KEY (DUENO_ID) 
    REFERENCES DUENO(ID_DUENO)
);

select * from proyecto;
select * from tarea;
commit;
SELECT ID_TAREA, PROYECTO_ID, TITULO
FROM TAREA
WHERE PROYECTO_ID IS NULL;

CREATE TABLE PROYECTO (
    ID NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(255),
    DESCRIPCION VARCHAR2(2000),
    RESPONSABLE VARCHAR2(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO VARCHAR2(50)
);

CREATE TABLE TAREA (
    ID_TAREA NUMBER(10) PRIMARY KEY,
    PROYECTO_ID NUMBER(10),
    TITULO VARCHAR2(255),
    DESCRIPCION VARCHAR2(2000),
    ASIGNADO_A VARCHAR2(100),
    FECHA_CREACION DATE,
    FECHA_VENCIMIENTO DATE,
    ESTADO VARCHAR2(50),
    PRIORIDAD VARCHAR2(50),
    
    -- Definición de la clave foránea (FK)
    FOREIGN KEY (PROYECTO_ID) REFERENCES PROYECTO(ID)
);


SELECT * FROM PROYECTO P
WHERE P.FECHA_FIN < SYSDATE 
  AND P.ESTADO != 'Terminado';
  
  SELECT * FROM TAREA
WHERE
    ESTADO != 'Completado'
    AND FECHA_VENCIMIENTO < TRUNC(SYSDATE);