spring.application.name=Producto

server.port=8011

#base de datos h2 en memoria

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=MARCO11
spring.datasource.password=CURSO2024
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

#eureka
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
