spring.application.name=Validadora


server.port=8001

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


receiver.url=http://localhost:8000/T


logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot.autoconfigure=INFO


