-- 1. Crear la tabla CURSO_ROLES
CREATE TABLE CURSO_ROLES (
    ID_ROL    NUMBER PRIMARY KEY,
    PRIVILEGIO NVARCHAR2(50) NOT NULL UNIQUE 
);

CREATE SEQUENCE CURSO_ROLES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CURSO_ROLES_TRG
BEFORE INSERT ON CURSO_ROLES
FOR EACH ROW
BEGIN
  :NEW.ID_ROL := CURSO_ROLES_SEQ.NEXTVAL;
END;
/

select * from CURSO_ROLES
;

-- 1. Crear la tabla CURSO_USUARIOS
CREATE TABLE CURSO_USUARIOS (
    ID_USUARIO      NUMBER PRIMARY KEY,
    NOMBRE          NVARCHAR2(100) NOT NULL,
    APP             NVARCHAR2(50) NOT NULL, 
    APM             NVARCHAR2(50),          
    SEXO            NVARCHAR2(25) NOT NULL,
    CORREO          NVARCHAR2(100) NOT NULL UNIQUE, 
    FECHA_NACIMIENTO DATE NOT NULL,
    FECHA_CREACION  DATE DEFAULT SYSDATE NOT NULL,
    ROL_ID          NUMBER NOT NULL,

    CONSTRAINT FK_ROL_ID
        FOREIGN KEY (ROL_ID)
        REFERENCES CURSO_ROLES(ID_ROL)
);

CREATE SEQUENCE CURSO_USUARIOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CURSO_USUARIOS_TRG
BEFORE INSERT ON CURSO_USUARIOS
FOR EACH ROW
BEGIN
  :NEW.ID_USUARIO := CURSO_USUARIOS_SEQ.NEXTVAL;
END;
/

INSERT INTO CURSO_ROLES (PRIVILEGIO) VALUES ('ADMINISTRADOR');
INSERT INTO CURSO_ROLES (PRIVILEGIO) VALUES ('GERENTE');
INSERT INTO CURSO_ROLES (PRIVILEGIO) VALUES ('COLABORADOR');
INSERT INTO CURSO_ROLES (PRIVILEGIO) VALUES ('BECARIO');

INSERT INTO CURSO_USUARIOS (NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) 
VALUES ('JUAN', 'PEREZ', 'GARCIA', 'MASCULINO', 'juan.perez@enucom.com.mx', DATE '1985-05-20', 1);

-- ID_ROL = 3 (COLABORADOR)
INSERT INTO CURSO_USUARIOS (NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) 
VALUES ('MARIA', 'LOPEZ', 'HERNANDEZ', 'FEMENINO', 'maria.lopez@enucom.com.mx', DATE '1992-11-15', 3);

-- ID_ROL = 2 (GERENTE)
INSERT INTO CURSO_USUARIOS (NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) 
VALUES ('CARLOS', 'RUIZ', NULL, 'MASCULINO', 'carlos.ruiz@enucom.com.mx', DATE '1978-08-01', 2); 

-- ID_ROL = 4 (BECARIO)
INSERT INTO CURSO_USUARIOS (NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) 
VALUES ('ANA', 'TORRES', 'SOTO', 'FEMENINO', 'ana.torres@enucom.com.mx', DATE '2000-02-29', 4); 


COMMIT;
