select * from prestamo
;

INSERT INTO PRESTAMO (IDPRESTAMO, FECHAINICIO, FECHAFIN, LIBRO_ID)
VALUES (23, DATE '2025-11-01', DATE '2025-11-15', 6);

-- 💡 Prueba esta sentencia si el nombre real es FECHA_FIN
INSERT INTO PRESTAMO (ID_PRESTAMO, FECHA_INICIO, FECHA_FIN, LIBRO_ID)
VALUES (23, DATE '2025-11-01', DATE '2025-11-15', 6);

SELECT COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'PRESTAMO';