select * from responsables;

select * from MASCOTAS;

UPDATE MASCOTA SET cliente_id = 3 WHERE id_mascota = 2;



CREATE TABLE MASCOTAS (
  ID_MASCOTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  RAZA VARCHAR2(100),
  EDAD NUMBER,
  RAZON_CITA VARCHAR2(255),
  CLIENTE_ID NUMBER,
  RESPONSABLE_ID NUMBER,
  VETERINARIA_ID NUMBER
);



