
DROP TABLE CELULAR_BIT;
DROP TABLE CELULAR;


CREATE TABLE CELULAR(
ID_CELULAR NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
RAM NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
PRECIO NUMBER,
CONSTRAINT CELU_PK PRIMARY KEY (ID_CELULAR)
);

-- TABLA DE BITÁCORA
CREATE TABLE CELULAR_BIT(
ID_BIT NUMBER, -- CLAVE PRIMARIA DE LA BITACORA
-- VALORES NUEVOS 
ID_CELULAR NUMBER,
MARCA NVARCHAR2(100),
MODELO NVARCHAR2(100),
RAM NVARCHAR2(100),
PROCESADOR NVARCHAR2(100),
PRECIO NUMBER,
-- VALORES VIEJOS 
MARCA_OLD NVARCHAR2(100),
MODELO_OLD NVARCHAR2(100),
RAM_OLD NVARCHAR2(100),
PROCESADOR_OLD NVARCHAR2(100),
PRECIO_OLD NUMBER,
-- CAMPOS DE CONTROL
USUARIO NVARCHAR2(100),
FECHA_MOV DATE,
MOVIMIENTO NVARCHAR2(100),
CONSTRAINT BIT_PK PRIMARY KEY(ID_BIT)
);



-- TRIGGER DE INSERT 
CREATE OR REPLACE TRIGGER TR_I_CELULAR
AFTER INSERT ON CELULAR
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT;

    INSERT INTO CELULAR_BIT(ID_BIT, ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD,
    PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL, NULL,
    NULL, NULL, LV_USUARIO, LV_FECHA, 'INSERT');

END;
/


-- TRIGGER DE DELETE 
CREATE OR REPLACE TRIGGER TR_D_CELULAR
AFTER DELETE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT;

    INSERT INTO CELULAR_BIT(
        ID_BIT,
        ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, PRECIO,
        MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
        USUARIO, FECHA_MOV, MOVIMIENTO
    )
    VALUES (
        LV_ID_BIT,
        :OLD.ID_CELULAR, NULL, NULL, NULL, NULL, NULL,
        :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO,
        LV_USUARIO, LV_FECHA, 'DELETE'
    );
END;
/

-- TRIGGER DE UPDATE 
CREATE OR REPLACE TRIGGER TR_U_CELULAR
AFTER UPDATE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    IF :OLD.MARCA <> :NEW.MARCA OR
       :OLD.MODELO <> :NEW.MODELO OR
       :OLD.RAM <> :NEW.RAM OR
       :OLD.PROCESADOR <> :NEW.PROCESADOR OR
       :OLD.PRECIO <> :NEW.PRECIO
    THEN
        SELECT USER INTO LV_USUARIO FROM DUAL;
        SELECT SYSDATE INTO LV_FECHA FROM DUAL;
        SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT;

        INSERT INTO CELULAR_BIT(
            ID_BIT,
            ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, PRECIO,
            MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES (
            LV_ID_BIT,
            :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO,
            :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO,
            LV_USUARIO, LV_FECHA, 'UPDATE'
        );
    END IF;
END;
/



INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'GALAXI F3', '4GB', 'OCTACORE', 5000);
INSERT INTO CELULAR VALUES (2, 'XIAOMI', 'REDMI NOTE 10', '6GB', 'SNAPDRAGON 678', 6500);
INSERT INTO CELULAR VALUES (3, 'MOTOROLA', 'G52', '8GB', 'SNAPDRAGON 680', 7200);


UPDATE CELULAR SET PRECIO = 5500, RAM = '6GB' WHERE ID_CELULAR = 1;

DELETE FROM CELULAR WHERE ID_CELULAR = 3;


SELECT * FROM CELULAR;
SELECT * FROM CELULAR_BIT;

COMMIT;