

CREATE TABLE LIBROS(
    ID_LIBROS NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    EDITORIAL NVARCHAR2(100),
    ISBN NUMBER
);

INSERT INTO LIBROS VALUES (1, 'IT', 'STEPHEN KING', 'PINGUIN', 4587149852367);
INSERT INTO LIBROS VALUES (2, 'Don Quijote de la Mancha', 'Miguel de Cervantes Saavedra', 'Espasa', 9788467032576);
INSERT INTO LIBROS VALUES (3, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Diana', 9780307389732);
INSERT INTO LIBROS VALUES (4, 'La sombra del viento', 'Carlos Ruiz Zafón', 'Planeta', 9788408172177);
INSERT INTO LIBROS VALUES (5, '1984', 'George Orwell', 'Debolsillo', 9788499890944);
INSERT INTO LIBROS VALUES (6, 'Fahrenheit 451', 'Ray Bradbury', 'Minotauro', 9788445071675);
INSERT INTO LIBROS VALUES (7, 'El principito', 'Antoine de Saint-Exupéry', 'Salamandra', 9788478887194);
INSERT INTO LIBROS VALUES (8, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Sudamericana', 9781400034956);
INSERT INTO LIBROS VALUES (9, 'Los miserables', 'Victor Hugo', 'Alianza Editorial', 9788420654181);
INSERT INTO LIBROS VALUES (10, 'Rayuela', 'Julio Cortázar', 'Alfaguara', 9788420471832);
COMMIT;

CREATE TABLE PRESTAMO(
    ID_PRESTAMO NUMBER PRIMARY KEY,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    LIBRO_ID NUMBER,
    CONSTRAINT FK_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBROS(ID_LIBROS)
);

INSERT INTO PRESTAMO VALUES (1, TO_DATE('2025-01-05', 'YYYY-MM-DD'), TO_DATE('2025-01-15', 'YYYY-MM-DD'), 1);
INSERT INTO PRESTAMO VALUES (2, TO_DATE('2025-02-10', 'YYYY-MM-DD'), TO_DATE('2025-02-20', 'YYYY-MM-DD'), 3);
INSERT INTO PRESTAMO VALUES (3, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-10', 'YYYY-MM-DD'), 3);
INSERT INTO PRESTAMO VALUES (4, TO_DATE('2025-03-15', 'YYYY-MM-DD'), TO_DATE('2025-03-25', 'YYYY-MM-DD'), 7);
INSERT INTO PRESTAMO VALUES (5, TO_DATE('2025-04-01', 'YYYY-MM-DD'), TO_DATE('2025-04-12', 'YYYY-MM-DD'), 2);
INSERT INTO PRESTAMO VALUES (6, TO_DATE('2025-04-20', 'YYYY-MM-DD'), TO_DATE('2025-04-30', 'YYYY-MM-DD'), NULL);
INSERT INTO PRESTAMO VALUES (7, TO_DATE('2025-05-05', 'YYYY-MM-DD'), TO_DATE('2025-05-15', 'YYYY-MM-DD'), 4);
INSERT INTO PRESTAMO VALUES (8, TO_DATE('2025-05-20', 'YYYY-MM-DD'), TO_DATE('2025-05-30', 'YYYY-MM-DD'), 6);
INSERT INTO PRESTAMO VALUES (9, TO_DATE('2025-06-01', 'YYYY-MM-DD'), TO_DATE('2025-06-10', 'YYYY-MM-DD'), 9);
INSERT INTO PRESTAMO VALUES (10, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-25', 'YYYY-MM-DD'), 10);
COMMIT;


SELECT * FROM LIBROS;
SELECT * FROM PRESTAMO;

//Muestra solo los préstamos que tienen libro.
SELECT *
FROM PRESTAMO P
INNER JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS;

//LEFT JOIN Muestra todos los préstamos, incluso los que no tienen libro

SELECT *
FROM PRESTAMO P
LEFT JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS;

//NULL
SELECT *
FROM PRESTAMO P
LEFT JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS
WHERE L.ID_LIBROS IS NULL;

//RIGHT JOIN Muestra todos los libros, incluso los que no tienen préstamo.

SELECT *
FROM PRESTAMO P
RIGHT JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS;

// solo los libros que no han sido prestados:

SELECT *
FROM PRESTAMO P
RIGHT JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS
WHERE P.LIBRO_ID IS NULL;

//FULL OUTER JOIN
//Muestra todos los préstamos y todos los libros, coincidan o no.

SELECT *
FROM PRESTAMO P
FULL JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS;

//solo los registros sin coincidencia en ambos lados:

SELECT *
FROM PRESTAMO P
FULL JOIN LIBROS L
ON P.LIBRO_ID = L.ID_LIBROS
WHERE P.LIBRO_ID IS NULL OR L.ID_LIBROS IS NULL;

