CREATE TABLE COMPUTADORA (
    ID INT PRIMARY KEY,
    MARCA NVARCHAR2(50),
    RAM INT, 
    ALMACENAMIENTO INT, 
    PROCESADOR NVARCHAR2(50),
    TIPO INT, 
    PRECIO DECIMAL(10, 2),
    FECHA_COMPRA DATE
);

INSERT INTO COMPUTADORA VALUES (1, 'HP', 16, 512, 'i7', 2, 18500.00, DATE '2023-01-15');
INSERT INTO COMPUTADORA VALUES (2, 'Dell', 8, 256, 'i5', 2, 12000.50, DATE '2024-03-20');
INSERT INTO COMPUTADORA VALUES (3, 'Apple', 32, 1024, 'M2', 3, 35000.99, DATE '2024-06-01');
INSERT INTO COMPUTADORA VALUES (4, 'Lenovo', 4, 500, 'Celeron', 1, 6500.00, DATE '2022-11-10');
INSERT INTO COMPUTADORA VALUES (5, 'Asus', 64, 2048, 'Ryzen 9', 1, 45000.00, DATE '2023-09-25');
INSERT INTO COMPUTADORA VALUES (6, 'Acer', 8, 1024, 'i5', 4, 15000.00, DATE '2024-04-05');
INSERT INTO COMPUTADORA VALUES (7, 'Samsung', 16, 1024, 'Snapdragon', 3, 11000.00, DATE '2023-07-07');

SELECT * FROM COMPUTADORA;

COMMIT;

//1.CLASIFICA LAS COMPUTADORAS POR CAPACIDAD DE RAM
SELECT
    MARCA,
    RAM,
    CASE
        WHEN RAM < 8 THEN 'BAJA Menos de 8GB'
        WHEN RAM >= 8 AND RAM < 16 THEN 'MEDIA 8GB o 12GB'
        ELSE 'ALTA 16GB o más'
    END AS CLASIFICACION_RAM
FROM
    COMPUTADORA;
    //    2.CLASIFICA LAS COMPUTADORA POR PRECIO

    SELECT
    MARCA,
    PRECIO,
    CASE
        WHEN PRECIO < 10000.00 THEN 'ECONOMICA'
        WHEN PRECIO BETWEEN 10000.00 AND 25000.00 THEN 'ESTANDAR'
        ELSE 'PREMIUM'
    END AS CLASIFICACION_PRECIO
FROM
    COMPUTADORA;
    
    //CLASIFICA LAS COMPUTADORS POR CAPACIDAD DE ALMACENAMIENTO.
    SELECT
    MARCA,
    ALMACENAMIENTO,
    CASE
        WHEN ALMACENAMIENTO <= 512 THEN 'BASICO Hasta 512GB'
        WHEN ALMACENAMIENTO > 512 AND ALMACENAMIENTO <= 1024 THEN 'NORMAL Hasta 1TB'
        ELSE 'GRAN CAPACIDAD Más de 1TB'
    END AS CLASIFICACION_ALMACENAMIENTO
FROM
    COMPUTADORA;
    
    // 4.-MUESTRA LA INFORMACION DE LA COMPUTADORA CON SU RESPECTIVO TIPO
    
    SELECT
    MARCA,
    PROCESADOR,
    RAM,
    ALMACENAMIENTO,
    PRECIO,
    CASE TIPO
        WHEN 1 THEN 'ESCRITORIO'
        WHEN 2 THEN 'PORTATIL'
        WHEN 3 THEN 'TABLET'
        WHEN 4 THEN 'TODO EN UNO'
        ELSE 'DESCONOCIDO'
    END AS TIPO_COMPUTADORA
FROM
    COMPUTADORA;
    
    //5.-CLASIFICA LAS COMPUTADORAS POR ANTIGUEDAD.
    
    SELECT
    MARCA,
    FECHA_COMPRA,
    TRUNC(SYSDATE - FECHA_COMPRA) AS DIAS_ANTIGUEDAD,
    CASE
        WHEN (SYSDATE - FECHA_COMPRA) < 270 THEN 'NUEVA (Menos de 9 meses)'
        WHEN (SYSDATE - FECHA_COMPRA) BETWEEN 366 AND 730 THEN 'SEMI-NUEVA (1 a 2 años)'
        ELSE 'ANTIGUA (Más de 2 años)'
    END AS CLASIFICACION_ANTIGUEDAD
FROM
    COMPUTADORA;
    
