// CREAR LA TABLA TRABAJADOR
CREATE TABLE TRABAJADOR (
    ID            NUMBER PRIMARY KEY,
    NOMBRE        NVARCHAR2(50),
    APELLIDO      NVARCHAR2(50),
    PUESTO        NVARCHAR2(50),
    DEPARTAMENTO  NVARCHAR2(50),
    SUELDO        NUMBER(10, 2)
);

--  AGREGAR POR LO MENOS 10 REGISTROS
INSERT INTO TRABAJADOR VALUES (1, 'Ana', 'García', 'Gerente', 'Ventas', 85000.00);
INSERT INTO TRABAJADOR VALUES (2, 'Luis', 'Martínez', 'Analista', 'Finanzas', 55000.50);
INSERT INTO TRABAJADOR VALUES (3, 'Sofía', 'Rodríguez', 'Desarrollador', 'IT', 62000.75);
INSERT INTO TRABAJADOR VALUES (4, 'Carlos', 'López', 'Asistente', 'Recursos Humanos', 35000.00);
INSERT INTO TRABAJADOR VALUES (5, 'Elena', 'Hernández', 'Gerente', 'Marketing', 78000.90);
INSERT INTO TRABAJADOR VALUES (6, 'Javier', 'Díaz', 'Técnico', 'Operaciones', 45000.00);
INSERT INTO TRABAJADOR VALUES (7, 'María', 'Sánchez', 'Contador', 'Finanzas', 58000.25);
INSERT INTO TRABAJADOR VALUES (8, 'Andrés', 'Pérez', 'Desarrollador', 'IT', 65000.00);
INSERT INTO TRABAJADOR VALUES (9, 'Laura', 'Gómez', 'Coordinador', 'Ventas', 49000.00);
INSERT INTO TRABAJADOR VALUES (10, 'Pablo', 'Vargas', 'Especialista', 'Marketing', 52000.50);

COMMIT; 

SELECT * FROM TRABAJADOR;

// PROCEDIMIENTO PARA CONSULTAR EL SUELDO DE UN TRABAJADOR
CREATE OR REPLACE PROCEDURE CONSULTAR_SUELDO (
    P_ID_TRABAJADOR IN  TRABAJADOR.ID%TYPE,
    P_SUELDO        OUT TRABAJADOR.SUELDO%TYPE
)
AS
BEGIN
    SELECT SUELDO
    INTO P_SUELDO
    FROM TRABAJADOR
    WHERE ID = P_ID_TRABAJADOR;


END;
/


DECLARE
     V_SUELDO NUMBER(10, 2);
BEGIN
CONSULTAR_SUELDO(1, V_SUELDO);
    IF V_SUELDO IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('EL SUELDO DEL TRABAJADOR ES: ' || V_SUELDO);
    END IF;
END;
/

// PROCEDIMIENTO PARA AUMENTAR EL SUELDO DE LOS TRABAJADORES
CREATE OR REPLACE PROCEDURE AUMENTAR_SUELDO_GLOBAL (
    P_PORCENTAJE_AUMENTO IN NUMBER
)
AS
BEGIN
   
    UPDATE TRABAJADOR
    SET SUELDO = SUELDO * (1 + P_PORCENTAJE_AUMENTO / 100);

    DBMS_OUTPUT.PUT_LINE('SE HA APLICADO UN AUMENTO DEL ' || P_PORCENTAJE_AUMENTO || '% A TODOS LOS TRABAJADORES.');
    
END;
/


EXECUTE AUMENTAR_SUELDO_GLOBAL(5); 
SELECT * FROM TRABAJADOR ;

ROLLBACK;
COMMIT;


// PROCEDIMIENTO PARA BUSCAR UN TRABAJADOR POR SU NOMBRE
CREATE OR REPLACE PROCEDURE BUSCAR_TRABAJADOR_POR_NOMBRE (
    P_NOMBRE_BUSCADO IN TRABAJADOR.NOMBRE%TYPE
)
AS
    CURSOR C_TRABAJADORES IS
        SELECT ID, APELLIDO, PUESTO, SUELDO
        FROM TRABAJADOR
        WHERE NOMBRE = P_NOMBRE_BUSCADO;

    V_CONTADOR NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('RESULTADOS DE BUSQUEDA:  ' || P_NOMBRE_BUSCADO );

    FOR R_TRABAJADOR IN C_TRABAJADORES LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || R_TRABAJADOR.ID || ' | APELLIDO: ' || R_TRABAJADOR.APELLIDO || 
                ' | PUESTO: ' || R_TRABAJADOR.PUESTO || 
                ' | SUELDO: ' || R_TRABAJADOR.SUELDO);
        V_CONTADOR := V_CONTADOR + 1;
    END LOOP;

    IF V_CONTADOR = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO TRABAJADOR CON ESTE NOMBRE ');
    END IF;

END;
/


EXECUTE BUSCAR_TRABAJADOR_POR_NOMBRE('JOSE');
