SELECT * FROM CELULAR;
DROP TABLE CELULAR_RESP;
--CREAR UNA TABLA DE RESPALDO
CREATE TABLE CELULAR_RESP(
    ID_CELULAR NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT CEL_PK_PK PRIMARY KEY(ID_CELULAR)
);

INSERT INTO CELULAR VALUES(1, 'MOTOROLA', 'MTOG20', '4GB', 'OCTACORE', 6000);
INSERT INTO CELULAR VALUES(2, 'SAMSUNG', 'GALAXY A32', '6GB', 'OCTACORE', 5000);
INSERT INTO CELULAR VALUES(3, 'APPLE', 'IPHONE 13', '4GB', 'HEXA-CORE', 4500);
INSERT INTO CELULAR VALUES(4, 'XIAOMI', 'REDMI NOTE 12', '8GB', 'OCTACORE', 5100);
INSERT INTO CELULAR VALUES(5, 'HUAWEI', 'P40 LITE', '6GB', 'OCTACORE', 4200);
INSERT INTO CELULAR VALUES(6, 'OPPO', 'A57', '4GB', 'OCTACORE', 5000);
INSERT INTO CELULAR VALUES(7, 'REALME', 'C35', '6GB', 'OCTACORE', 5000);
INSERT INTO CELULAR VALUES(8, 'NOKIA', 'G50', '4GB', 'OCTACORE', 5050);
INSERT INTO CELULAR VALUES(9, 'HONOR', 'X8', '6GB', 'OCTACORE', 4000);
INSERT INTO CELULAR VALUES(10, 'ZTE', 'BLADE V40', '4GB', 'OCTACORE', 5000);

//PROCEDIMIENTO ALMACENADO COMO TAREA DE RESPALDO LO QUE EXISTA EN LA TABLA CELULAR 
CREATE OR REPLACE PROCEDURE PR_RESPALDO_CELULAR
IS
    --DECLARACION DE VARIABLES, CONSTANTES O CURSORES
BEGIN
    --INSTRUCCION DE ELIMINAR
    DELETE FROM CELULAR_RESP;
    --REALIZAR EL RESPALDO
    INSERT INTO CELULAR_RESP(ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
        SELECT ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM CELULAR;
END;
/

EXECUTE PR_RESPALDO_CELULAR;
SELECT * FROM CELULAR;
SELECT * FROM CELULAR_RESP;

-- PROCEDIMIENTO PARA APLICAR UN DESCUENTO
CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO(P_DESCUENTO IN NUMBER) -- EL PORCENTAJE DESCUENTO 10%, 15%
IS
BEGIN
    UPDATE CELULAR
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100));

    DBMS_OUTPUT.PUT_LINE('SE APLICO EL DESCUENTO DEL ' || P_DESCUENTO || '% A TODOS LOS CELULARES');
END;
/

SELECT * FROM CELULAR;
EXECUTE APLICAR_DESCUENTO(10);
ROLLBACK;
COMMIT;

SELECT * FROM ALUMNO;


