--UNA VISTA QUE MUESTRE EL NOMBRE, DEPARTAMENTO Y PUESTO DE TODOS LOS TRABAJADORES
CREATE OR REPLACE VIEW V_TRABAJADOR_INFO AS
SELECT
    NOMBRE,
    DEPARTAMENTO,
    PUESTO
FROM
    TRABAJADOR;


SELECT * FROM V_TRABAJADOR_INFO;

-- 2. UNA VISTA QUE MUESTRE EL NOMBRE Y EDAD DE LOS EMPLEADOS DEL DEPARTAMENTO DE 'TECNOLOGIA'


SELECT * FROM TRABAJADOR;
CREATE OR REPLACE VIEW V_TECNOLOGIA_EDAD AS
SELECT
    NOMBRE
FROM
    TRABAJADOR
WHERE
    DEPARTAMENTO = 'IT';


SELECT * FROM V_TECNOLOGIA_EDAD;


-- 3. UNA VISTA QUE MUESTRE LOS TRABAJADORES QUE GANAN MENOS DE 70000
CREATE OR REPLACE VIEW V_SUELDO_BAJO AS
SELECT
    NOMBRE,
    APELLIDO,
    SUELDO
FROM
    TRABAJADOR
WHERE
    SUELDO < 70000;


SELECT * FROM V_SUELDO_BAJO;

-- 4. UNA VISTA QUE MUESTRE EL NOMBRE, APELLIDO Y DEPARTAMENTO DE LOS TRABAJADORES Y LOS CATALOGUE POR SUELDO (ALTO, MEDIO, BAJO).
CREATE OR REPLACE VIEW V_TRABAJADOR_CATEGORIA AS
SELECT
    NOMBRE,
    APELLIDO,
    DEPARTAMENTO,
    SUELDO,
    CASE
        WHEN SUELDO > 51000 THEN 'ALTO'     
        WHEN SUELDO BETWEEN 20000 AND 50000 THEN 'MEDIO'   
        ELSE 'BAJO'                         
    END AS CATEGORIA_SUELDO
FROM
    TRABAJADOR;


SELECT * FROM V_TRABAJADOR_CATEGORIA;