CREATE OR REPLACE FUNCTION SUMA(a NUMBER, b NUMBER)
RETURN NUMBER
IS
    RESULTADO NUMBER;
BEGIN
    RESULTADO := a + b;
    RETURN RESULTADO;
END;
/

-- IMPRIMIR EL RESULTADO EN DUAL
SELECT SUMA(10, 15) FROM DUAL;

-- INVOCAR DESDE UN BLOQUE ANÓNIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL RESULTADO DE LA SUMA ES: ' || SUMA(1, 2));
END;
/

CREATE OR REPLACE FUNCTION AREA_CIRCULO(RADIO NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN 3.1416 * (RADIO * RADIO);
END;
/

-- MEDIANTE UN CONSULTA
SELECT AREA_CIRCULO(5) FROM DUAL;

-- MEDIANTE UN BLOQUE ANÓNIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL AREA DEL CIRCULO ES: ' || AREA_CIRCULO(6));
END;
/

//CALCULA EL ÁREA DE UN TRIÁNGULO
CREATE OR REPLACE FUNCTION CALC_AREA_TRIANGULO (
    P_BASE IN NUMBER,
    P_ALTURA IN NUMBER
)
RETURN NUMBER
IS
    V_AREA NUMBER;
BEGIN
    V_AREA := (P_BASE * P_ALTURA) / 2;
    RETURN V_AREA;
END;
/


SELECT 'ÁREA DEL TRIÁNGULO ES: ' || CALC_AREA_TRIANGULO(23, 13) AS RESULTADO FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('EL AREA DEL TRIANGULO ES: ' || CALC_AREA_TRIANGULO(10, 5));
END;

//FUNCIÓN QUE RECIBE UN NÚMERO Y DEVUELVE SI ES PAR O IMPAR

CREATE OR REPLACE FUNCTION ES_PAR_O_IMPAR (
    P_NUMERO IN NUMBER
)
RETURN NVARCHAR2
IS
BEGIN
    IF MOD(P_NUMERO, 2) = 0 THEN
        RETURN 'PAR';
    ELSE
        RETURN 'IMPAR';
    END IF;
END;
/

SELECT ES_PAR_O_IMPAR(7) AS ES_SIETE, ES_PAR_O_IMPAR(12) AS ES_DOCE FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('EL NUMERO 5 ES: ' || ES_PAR_O_IMPAR(5)
    || '  EL NUMERO 20 ES:' ||ES_PAR_O_IMPAR(20));
END;


//CALCULA LA EDAD A PARTIR DE UNA FECHA DE NACIMIENTO

CREATE OR REPLACE FUNCTION CALC_EDAD (
    P_FECHA_NACIMIENTO IN DATE
)
RETURN NUMBER
IS
    V_EDAD NUMBER;
BEGIN
    V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, P_FECHA_NACIMIENTO) / 12);
    RETURN V_EDAD;
END;
/


SELECT 'LA EDAD ES: ' || CALC_EDAD(TO_DATE('1998-10-23', 'YYYY-MM-DD')) AS RESULTADO FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('LA EDAD ES: ' || calc_edad(TO_DATE('1998-10-23', 'YYYY-MM-DD')) );
END;

//RECIBE NOMBRE Y APELLIDO Y DEVUELVE LAS INICIALES

CREATE OR REPLACE FUNCTION OBTENER_INICIALES (
    P_NOMBRE IN NVARCHAR2,
    P_APELLIDO IN NVARCHAR2
)
RETURN NVARCHAR2
IS
    V_INICIALES NVARCHAR2(5);
BEGIN
    V_INICIALES := SUBSTR(P_NOMBRE, 1, 1) || '.' || SUBSTR(P_APELLIDO, 1, 1);
    RETURN (V_INICIALES);
END;
/

SELECT OBTENER_INICIALES('JOSUE ', 'HERNANDEZ') AS INICIALES FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('LAS INICIALES SON SON: ' || OBTENER_INICIALES('JOSUE ', 'HERNANDEZ') );
END;

//DEVUELVE EL NOMBRE DEL MES CORRESPONDIENTE (1 AL 12)

CREATE OR REPLACE FUNCTION OBTENER_NOMBRE_MES (
    P_NUMERO_MES IN NUMBER
)
RETURN NVARCHAR2
IS
    V_FECHA_BASE DATE;
BEGIN
    IF P_NUMERO_MES < 1 OR P_NUMERO_MES > 12 THEN
        RETURN 'MES INVÁLIDO';
    END IF;
 
    V_FECHA_BASE := TO_DATE('01-' || P_NUMERO_MES || '-2000', 'DD-MM-YYYY');

    RETURN TO_CHAR(V_FECHA_BASE, 'MONTH');
END;
/

SELECT OBTENER_NOMBRE_MES(10) FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('EL MES QUE INTRODUJO ES: ' || OBTENER_NOMBRE_MES(11) );
END;
