--EJEMPLO DE CURSI EXPLICITO
CREATE OR REPLACE PROCEDURE DETALLE_CELULARES
IS
    CURSOR CELULARES_LISTA IS
        SELECT MARCA, MODELO, PRECIO FROM CELULAR;

    V_MARCA CELULAR.MARCA%TYPE;
    V_MODELO CELULAR.MODELO%TYPE;
    V_PRECIO CELULAR.PRECIO%TYPE;
BEGIN
    OPEN CELULARES_LISTA;
    LOOP
        FETCH CELULARES_LISTA INTO V_MARCA, V_MODELO, V_PRECIO; --RECUPERACION DE LA FILA
        EXIT WHEN CELULARES_LISTA%NOTFOUND; --SALIR CUANDO YA NO ENCUENTRE NINGUNA FILA
        DBMS_OUTPUT.PUT_LINE('EL CELULAR: ' || V_MARCA || ' ' || V_MODELO || ' TIENE UN PRECIO DE: ' || V_PRECIO);

END LOOP;
CLOSE CELULARES_LISTA;

END;
/
EXECUTE DETALLE_CELULARES;

select * from trabajador;
ALTER TABLE TRABAJADOR
ADD (EDAD NUMBER(3));


DECLARE CURSOR C_TRABAJADOR IS
        SELECT NOMBRE, APELLIDO, EDAD
        FROM TRABAJADOR;

    V_NOMBRE TRABAJADOR.NOMBRE%TYPE;
    V_APELLIDO TRABAJADOR.APELLIDO%TYPE;
    V_EDAD TRABAJADOR.EDAD%TYPE;

BEGIN
    OPEN C_TRABAJADOR;

    LOOP
        FETCH C_TRABAJADOR INTO V_NOMBRE, V_APELLIDO, V_EDAD;

        EXIT WHEN C_TRABAJADOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('TRABAJADOR: ' || V_NOMBRE || ' ' || V_APELLIDO || ' | EDAD: ' || V_EDAD);
    END LOOP;

    CLOSE C_TRABAJADOR;

END;
/

SELECT * FROM ALUMNO;

DECLARE CURSOR C_ESTUDIANTES_SISTEMAS IS
        SELECT ID, NOMBRE, CARRERA, PROMEDIO, GENERO
        FROM ALUMNO
        WHERE CARRERA = 'Sistemas';

    R_ESTUDIANTE C_ESTUDIANTES_SISTEMAS%ROWTYPE;

BEGIN
    DBMS_OUTPUT.PUT_LINE('ESTUDIANTES DE SISTEMAS');
    
    OPEN C_ESTUDIANTES_SISTEMAS;

    LOOP
        FETCH C_ESTUDIANTES_SISTEMAS INTO R_ESTUDIANTE;

        EXIT WHEN C_ESTUDIANTES_SISTEMAS%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('ID: ' || R_ESTUDIANTE.ID || 
                             ' | NOMBRE: ' || R_ESTUDIANTE.NOMBRE || 
                             ' | CARRERA: ' || R_ESTUDIANTE.CARRERA || 
                             ' | PROMEDIO: ' || R_ESTUDIANTE.PROMEDIO ||
                             ' | GÉNERO: ' || R_ESTUDIANTE.GENERO);
    END LOOP;

    CLOSE C_ESTUDIANTES_SISTEMAS;

END;
/