
CREATE TABLE SALA (
  ID_SALA     NUMBER PRIMARY KEY,
  NOMBRE      NVARCHAR2(100),
  CAPACIDAD   NUMBER,
  TIPO        NUMBER  -- 1=TRADICIONAL, 2=VIP, 3=IMAX
);

INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('1', 'VIVALDI',   120, 2);  
INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('2', 'MOZART',    200, 1);  
INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('3', 'BEETHOVEN', 250, 3);  
INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('4', 'CHOPIN',     NULL, 1); 
INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('5', 'DEBUSSY',     80,  NULL); 
INSERT INTO SALA (ID_SALA, NOMBRE, CAPACIDAD, TIPO) VALUES ('6', 'LISZT',      150, 2); 


CREATE TABLE FUNCION (
  ID_FUNCION     NUMBER PRIMARY KEY,
  PELICULA       NVARCHAR2(100),
  DURACION_MIN   NUMBER,
  GENERO         NVARCHAR2(50),
  PRECIO_BOLETO  NUMBER(10,2),
  SALA_ID        NUMBER,
  CONSTRAINT FK_FUNCION_SALA FOREIGN KEY (SALA_ID) REFERENCES SALA(ID_SALA)
);

INSERT INTO FUNCION VALUES(101, 'TITANIC', 195, 'DRAMA', 120.00, 1);    
INSERT INTO FUNCION VALUES(102, 'INCEPTION',  148, 'SCI-FI', 150.00, 3);   
INSERT INTO FUNCION VALUES(103, 'COCO', 105, 'ANIMACIÓN', 85.00, 2);  
INSERT INTO FUNCION VALUES(104, 'AVATAR', 162, 'SCI-FI', 180.00, NULL); 
INSERT INTO FUNCION VALUES(105, 'PARASITE',   132, 'DRAMA', NULL, 5);     
INSERT INTO FUNCION VALUES(106, 'UP',NULL, 'ANIMACIÓN', 90.00, NULL); 


//1MOSTRAR TODAS LA FUNCIONES CON EL NOMBRE DE LA SALA Y EL TIPO DE SALA USANDO CASE.
SELECT
  F.ID_FUNCION,
  F.PELICULA,
  S.NOMBRE AS SALA,
  CASE S.TIPO
    WHEN 1 THEN 'TRADICIONAL'
    WHEN 2 THEN 'VIP'
    WHEN 3 THEN 'IMAX'
    ELSE 'SIN TIPO'
  END AS TIPO_SALA
FROM FUNCION F
LEFT JOIN SALA S ON S.ID_SALA = F.SALA_ID;


//2 .CONTAR CUANTAS FUNCIONES HAY POR EGENRO
SELECT
  NVL(GENERO, 'SIN GÉNERO') AS GENERO,
  COUNT(*) AS TOTAL
FROM FUNCION
GROUP BY GENERO
ORDER BY TOTAL DESC;

//3 MOSTRAR LA FUNCION CON EL BOLETO MAS CARO Y AGREGAR LA PALABRA "PESOS" AL FINAL
SELECT
  PELICULA,
  TO_CHAR(PRECIO_BOLETO) || ' PESOS' AS PRECIO_MAS_CARO
FROM FUNCION
WHERE PRECIO_BOLETO IS NOT NULL
ORDER BY PRECIO_BOLETO DESC
FETCH FIRST 1 ROWS ONLY;

//4 MOSTRAR EL TOTAL DE BOLETOS QUE PODRIA VENDFER CADA FUNCION(CAPACIDAD DE LA SALA * PRECIO BOLETO)
SELECT
  F.ID_FUNCION,
  F.PELICULA,
  S.NOMBRE AS SALA,
  NVL(S.CAPACIDAD, 0) * NVL(F.PRECIO_BOLETO, 0) AS TOTAL
FROM FUNCION F
LEFT JOIN SALA S ON S.ID_SALA = F.SALA_ID
ORDER BY F.ID_FUNCION;

//5 -MOSTRAR LA SALA CON MAYOR ACPACIDAD Y CONCATENAR EL RESULTADO CON LA PALBRA "AISENTOS"
SELECT
  S.NOMBRE || ' - ' || TO_CHAR(S.CAPACIDAD) || ' ASIENTOS' AS SALA_MAYOR_CAPACIDAD
FROM SALA S
WHERE S.CAPACIDAD IS NOT NULL
ORDER BY S.CAPACIDAD DESC
FETCH FIRST 1 ROWS ONLY;

//6 MOSTRAR LAS FUNCIONES QUE NO TIENEN SALA ASIGNADA
SELECT * FROM FUNCION
WHERE SALA_ID IS NULL;

//7 ORDENAR LAS FUNCIONAS PRIMEROS POR GENERO Y LUEGO POR DURACION(ES SOLO UN CONSULTA)
SELECT * FROM FUNCION
ORDER BY GENERO, DURACION_MIN;

//8 MOSTRAR EL DETALLE DE LAS FUNCIONES CON PIPES ||
SELECT
  'LA PELÍCULA ' || NVL(F.PELICULA, '(SIN TÍTULO)') ||
  ' SE PROYECTA EN LA SALA ' || NVL(S.NOMBRE, '(SIN SALA)') ||
  ' DE TIPO ' ||
    CASE S.TIPO
      WHEN 1 THEN 'TRADICIONAL'
      WHEN 2 THEN 'VIP'
      WHEN 3 THEN 'IMAX'
      ELSE 'SIN TIPO'
    END ||
  ' CON UNA DURACIÓN DE ' || NVL(TO_CHAR(F.DURACION_MIN), '(S/D)') ||
  ' MINUTOS' AS DETALLE
FROM FUNCION F
LEFT JOIN SALA S ON S.ID_SALA = F.SALA_ID;

//9 MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE
SELECT GENERO, COUNT(*) AS TOTAL
FROM FUNCION
GROUP BY GENERO
ORDER BY TOTAL DESC 
FETCH FIRST 1 ROWS ONLY;


