create table EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APATERNO NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
    
);

INSERT INTO EMPLEADO VALUES(1, 'MARTIN', 'LOPEZ', 35, 'RPOGRAMACION JAVA', 'DESARROLLO');
COMMIT;

SELECT * FROM EMPLEADO;

DROP TABLE EMPLEADO;

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APATERNO NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);