SELECT * FROM EMPLEADO;

INSERT INTO EMPLEADO VALUES(1, 'MARTIN', 'LOPEZ', 32, 'RPOGRAMACION JAVA', 'DESARROLLO');
INSERT INTO EMPLEADO VALUES(2, 'ANA', 'GARCIA', 25, 'EJECUTIVA COMERCIAL', 'VENTAS');
INSERT INTO EMPLEADO VALUES(3, 'MELANY', 'SANCHEZ', 26, 'SECRETARIA', 'DEP. RH');
INSERT INTO EMPLEADO VALUES(4, 'ALFREDO', 'GODOFREDO', 32, 'MANAGER', 'DEP. IT');
INSERT INTO EMPLEADO VALUES(5, 'BEATRIZ', 'MARTINEZ', 29, 'ANALISTA', 'DEP. VENTAS');
INSERT INTO EMPLEADO VALUES(6, 'MAURICIO', 'RAMIREZ', 28, 'PROGRAMADOR Jr', 'DEP. IT');
COMMIT;

ALTER TABLE EMPLEADO RENAME COLUMN APATERNO TO APELLIDO;

--ACTUALIZAR UN REGISTRO
UPDATE EMPLEADO SET NOMBRE = 'MARTINA' WHERE ID_EMPLEADO = 6;

--ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY NOMBRE DESC;

--BUSQUEDA DE INFORMACION CON CARACTERES EN ESPECIFICO
--BUSCAR EMPLEADOS QUE SU NOMBRE EMPIEZA CON LA LETRA A
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'A%';
--BUSCAR EMPLEADOS QUE SU NOMBRE CONTENGA UNA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';
--BUSCAR EMPLEADOS QUE SU NOMBRE FINALICE CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--USO DE LA TABLA DUAL: ES UNA TABLA DE ORACLE A LA QUE PODEMOS ACCEDER CUANDO NO SE NECESITA
--ACCEDER A UNA TABLA REAL
SELECT 5 + 7 AS SUMA FROM DUAL;

--USO LA FUNCION LENGTH
SELECT LENGTH('ESTE ES UN EJEMPLO PARA EL USO DE LA FUNCION LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADO QUE TENGAN 32
SELECT * FROM EMPLEADO WHERE EDAD = 32;
--MAYORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD > 30;
--MENORES DE 29
SELECT * FROM EMPLEADO WHERE EDAD < 29;

--EMPLEADOS MAYORES DE 25 PERO MENORES DE 28
SELECT * FROM EMPLEADO WHERE EDAD > 25 AND EDAD < 28;
--RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 25 AND 28;

--BUSCAR SOLO LOS EMPLEADOS CON ID 1, 5 Y 7
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 5 OR ID_EMPLEADO = 6;
--FUNCION
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1, 5, 6);

--AGRUPAR LOS EMPLEADOS POR DEPARTAMENTO (GROUP BY, COUNT)
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO GROUP BY DEPARTAMENTO;

--CONTAR CUANTOS EMPLEADOS SON MAYORES DE 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD > 25;

--FUNCION SUM
SELECT SUM(EDAD) AS SUMA_EDAD FROM EMPLEADO;
SELECT SUM(EDAD) AS SUMA_EDAD FROM EMPLEADO WHERE NOMBRE LIKE '%I%';

--CUAL ES LA EDAD MAS GRANDE (MAX)
SELECT MAX(EDAD) FROM EMPLEADO;

--CUAL ES LA EDAD MINIMA (MIN)
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

SELECT 
    'EL EMPLEADO: ' || NOMBRE || ' ' || APELLIDO || 
    ' DE EDAD ' || EDAD || 
    ' TRABAJA COMO: ' || PUESTO || 
    ' EN EL DEPARTAMENTO: ' || DEPARTAMENTO
FROM 
    EMPLEADO;
    
    --SUBCONSULTA
SELECT * FROM EMPLEADO WHERE
EDAD = (
    SELECT MIN(EDAD)
    FROM EMPLEADO WHERE DEPARTAMENTO = ('DEP. IT')
);