
DROP TABLE PELICULA;
CREATE TABLE PELICULA(
    ID_PELICULA NUMBER,
    NOMBRE NVARCHAR2(100),
    DIRECTOR NVARCHAR2(100),
    DURACION NUMBER,
    GENERO NUMBER, --1COMEDIA,2TERROR,3DRAMA,4SUSPENSO,5ACCION,6CATASTORFE,7DOCUMENTALES
    PRODUCTORA NVARCHAR2(100),
    CONSTRAINT PELI_PK PRIMARY KEY(ID_PELICULA)
);

INSERT INTO PELICULA VALUES (1, 'LO IMPOSIBLE', 'JUAN ANTONIO BAYONA', 105, 6, 'ALVARO');
INSERT INTO PELICULA VALUES (2, 'HP Y PRISIONERO DE AZKABAN', 'ALFONSO CUERON', 0, 0, 'CHRIS COLOMBUS');
INSERT INTO PELICULA VALUES (3, 'La La Land', 'Damien Chazelle', 128, 3, 'Summit Entertainment');
INSERT INTO PELICULA VALUES (4, 'El Origen', 'Christopher Nolan', 148, 4, 'Warner Bros.');
INSERT INTO PELICULA VALUES (5, 'Vengadores: Endgame', 'Hermanos Russo', 181, 5, 'Marvel Studios');
INSERT INTO PELICULA VALUES (6, 'Lo Imposible', 'J. A. Bayona', 114, 6, 'Warner Bros. España');
INSERT INTO PELICULA VALUES (7, 'The Social Dilemma', 'Jeff Orlowski', 94, 7, 'Netflix');
INSERT INTO PELICULA VALUES (8, 'Borat', 'Larry Charles', 84, 1, '20th Century Fox');
INSERT INTO PELICULA VALUES (9, 'El Resplandor', 'Stanley Kubrick', 146, 2, 'Warner Bros.');
INSERT INTO PELICULA VALUES (10, 'Una Mente Maravillosa', 'Ron Howard', 135, 3, 'Universal Pictures');
INSERT INTO PELICULA VALUES (11, 'Seven', 'David Fincher', 127, 4, 'New Line Cinema');
INSERT INTO PELICULA VALUES (12, 'John Wick', 'Chad Stahelski', 101, 5, 'Lionsgate');
INSERT INTO PELICULA VALUES (13, '2012', 'Roland Emmerich', 158, 6, 'Columbia Pictures');
INSERT INTO PELICULA VALUES (14, 'Free Solo', 'Jimmy Chin', 100, 7, 'National Geographic');
INSERT INTO PELICULA VALUES (15, 'Mi Vecino Totoro', 'Hayao Miyazaki', 86, 1, 'Studio Ghibli');
INSERT INTO PELICULA VALUES (16, 'IT', 'Andy Muschietti', 135, 2, 'New Line Cinema');

COMMIT;

SELECT * FROM PELICULA;

SELECT ID_PELICULA, NOMBRE, DIRECTOR, DURACION,
(
    CASE GENERO
        WHEN 1 THEN 'COMEDIA'
        WHEN 2 THEN 'TERROR'
        WHEN 3 THEN 'DRAMA'
        WHEN 4 THEN 'SUSPENSO'
        WHEN 5 THEN 'ACCION'
        WHEN 6 THEN 'CATASTROFE'
        WHEN 7 THEN 'DOCUMENTAL'
        ELSE 'SIN GENERO'
    END
) AS GENERO, PRODUCTORA FROM PELICULA;


SELECT NOMBRE, DIRECTOR,
(
    CASE
        WHEN DURACION < 100 THEN 'CORTA'
        WHEN DURACION BETWEEN 100 AND 130 THEN 'MEDIA'
        ELSE 'LARGA'
    END
) AS DURACION, GENERO, PRODUCTORA FROM PELICULA;