

-- 1. CREAR LA ENTIDAD
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    CATEGORIA NVARCHAR2(50),
    PRECIO NUMBER(10, 2),
    CONSTRAINT PROD_PK PRIMARY KEY (ID_PRODUCTO)
);

-- 2. CREAR LA BITÁCORA DE ESA ENTIDAD
CREATE TABLE PRODUCTO_BIT (
    ID_BIT NUMBER,
    -- CAMPOS DE FILA
    ID_PRODUCTO_OLD NUMBER,
    NOMBRE_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER(10, 2),
    ID_PRODUCTO_NEW NUMBER,
    NOMBRE_NEW NVARCHAR2(100),
    PRECIO_NEW NUMBER(10, 2),
    -- CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(25),
    CONSTRAINT BIT_PROD_PK PRIMARY KEY (ID_BIT)
);

-- 3. CREAR LA SEQUENCIA PARA APLICAR Y UTILIZAR CON ESA ENTIDAD
CREATE SEQUENCE ID_BIT_PROD
START WITH 1
INCREMENT BY 1
NOCACHE;
/

-- 4. TRIGGER MULTIPLE DE TIPO AFTER A NIVEL FILA
CREATE OR REPLACE TRIGGER TR_FILA_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOVIMIENTO NVARCHAR2(15);
BEGIN
    SELECT ID_BIT_PROD.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN
        LV_MOVIMIENTO := 'INSERT';
        INSERT INTO PRODUCTO_BIT (ID_BIT, ID_PRODUCTO_NEW, NOMBRE_NEW, PRECIO_NEW, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :NEW.ID_PRODUCTO, :NEW.NOMBRE, :NEW.PRECIO, LV_USUARIO, LV_FECHA, LV_MOVIMIENTO);

    ELSIF UPDATING THEN
        LV_MOVIMIENTO := 'UPDATE';
        INSERT INTO PRODUCTO_BIT (ID_BIT, ID_PRODUCTO_OLD, NOMBRE_OLD, PRECIO_OLD, ID_PRODUCTO_NEW, NOMBRE_NEW, PRECIO_NEW, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :OLD.ID_PRODUCTO, :OLD.NOMBRE, :OLD.PRECIO, :NEW.ID_PRODUCTO, :NEW.NOMBRE, :NEW.PRECIO, LV_USUARIO, LV_FECHA, LV_MOVIMIENTO);

    ELSIF DELETING THEN
        LV_MOVIMIENTO := 'DELETE';
        INSERT INTO PRODUCTO_BIT (ID_BIT, ID_PRODUCTO_OLD, NOMBRE_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :OLD.ID_PRODUCTO, :OLD.NOMBRE, :OLD.PRECIO, LV_USUARIO, LV_FECHA, LV_MOVIMIENTO);
    END IF;
END;
/

-- 5. TRIGGER MULTIPLE DE TIPO AFTER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_SENTENCIA_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOVIMIENTO NVARCHAR2(25) := 'SENTENCIA'; 
BEGIN
    SELECT ID_BIT_PROD.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN
        LV_MOVIMIENTO := LV_MOVIMIENTO || ' (INSERT)';
    ELSIF UPDATING THEN
        LV_MOVIMIENTO := LV_MOVIMIENTO || ' (UPDATE)';
    ELSIF DELETING THEN
        LV_MOVIMIENTO := LV_MOVIMIENTO || ' (DELETE)';
    END IF;

    INSERT INTO PRODUCTO_BIT (ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOVIMIENTO);
END;
/


-- PRUEBAS


DELETE FROM PRODUCTO;
DELETE FROM PRODUCTO_BIT;
COMMIT;


INSERT INTO PRODUCTO VALUES (10, 'Teclado Mecánico', 'Electrónica', 85.00);
INSERT INTO PRODUCTO VALUES (20, 'Mouse Ergonómico', 'Electrónica', 30.50);
INSERT INTO PRODUCTO VALUES (30, 'Monitor Curvo 27"', 'Electrónica', 450.00);


UPDATE PRODUCTO SET PRECIO = PRECIO * 1.10 WHERE CATEGORIA = 'Electrónica' AND ID_PRODUCTO < 30;

DELETE FROM PRODUCTO WHERE PRECIO >50;

COMMIT;

SELECT * FROM PRODUCTO_BIT;