DELETE FROM CELULAR;
DELETE FROM CELULAR_BIT;

CREATE OR REPLACE TRIGGER TR_SENTENCIA_CEL
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
----FOR EACH ROW (NO APLICA PORQUE ES POR SENTENCIA)
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
LV_MOV NVARCHAR2(10);
BEGIN
SELECT ID_BIT_CEL.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

IF INSERTING THEN
LV_MOV := 'INSERT';
ELSIF UPDATING THEN
LV_MOV := 'UPDATE';
ELSIF DELETING THEN
LV_MOV := 'DELETE';
END IF;

INSERT INTO CELULAR_BIT(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
VALUES (LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);

END;
/
SELECT * FROM CELULAR;
SELECT * FROM CELULAR_BIT;
INSERT INTO CELULAR VALUES (1, 'MOTOROLA', 'MOTO G20', '4GB', 'OCTACORE', 5237);
INSERT INTO CELULAR VALUES (2, 'SAMSUNG', 'GALAXI SFE3', '4GB', 'OCTACORE', 2300);
UPDATE CELULAR SET RAM = '8GB' WHERE ID_CELULAR = 2;
DELETE FROM CELULAR;