SELECT USER FROM DUAL;
SELECT SYSDATE FROM DUAL;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';


--TRIGGER QUE ACTUARA CUANDO OCURRA UNA OPERACION DE TIPO INSERT, DELETE OR UPDATE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_CEL
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
BEGIN
--RECUPERAR UN ID VALIDO USANDO SECUENCIAS