spring.application.name=EurekaServer
#Configuracion del puerto
server.port=8761

#configuracion de Eureka
#Nombre del host donde se esta ejecutando la instancia
eureka.instance.hostname=localhost
#especificar el url del servidor al que debe conectarse y descubrir otros microservicios
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#indicar que el cliente no debe registrarse
eureka.client.register-with-eureka=false
#indicar que el cliente no debe obtener el registro d los demas ms
eureka.client.fetch-registry=false
#ayuda contra perdidad de instancias
eureka.server.enable-self-preservation=true
#exponer todos los endpoint administrados
management.endpoints.web.exposure.include=*
#mostrar el estado de salud de la aplicacion
management.endpoint.health.show-details=always